---
name: YAML Lint
description: A Buildkite plugin to check YAML files and syntax errors
author: https://msha.ke/johnsyweb/
requirements:
  - docker
configuration:
  properties:
    pattern:
      type: string
    version:
      type: string
