#!/bin/bash
set -euo pipefail

PATTERN="${BUILDKITE_PLUGIN_YAMLLINT_PATTERN:-*.*yaml}"
YAMLLINT_VERSION="${BUILDKITE_PLUGIN_YAMLLINT_VERSION:-latest}"

echo "--- :yaml: checking YAML files (${PATTERN})..."

errors=0
find . -name "${PATTERN}" -exec docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "cytopia/yamllint:${YAMLLINT_VERSION}" {} + || errors=1

if [[ ${errors} -lt 1 ]]
then
    echo "Beautiful!"
else
    echo "Mistakes were made."
fi

exit ${errors}
